<a href="https://colab.research.google.com/github/rodricard/Normalizacion-de-datos-/blob/main/Normalizacion_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas scikit-learn -q

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df = pd.read_csv('/content/ventas.csv.csv', encoding='latin1')

In [ ]:
print("DATASET ORIGINAL")
display(df.head())

DATASET ORIGINAL

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [ ]:
scaler = MinMaxScaler()

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [ ]:
print("DATASET NORMALIZADO")
display(df.head())

DATASET NORMALIZADO

,ordernumber,quantityordered,priceeach,orderlinenumber,sales,orderdate,status,qtr_id,month_id,year_id,...,addressline1,addressline2,city,state,postalcode,country,territory,contactlastname,contactfirstname,dealsize
0,0.021538,0.263736,0.941193,0.058824,0.175644,2/24/2003 0:00,shipped,0.000000,0.090909,0.0,...,897 long airport avenue,nan,nyc,ny,10022,usa,nan,yu,kwai,small
1,0.064615,0.307692,0.744940,0.235294,0.167916,5/7/2003 0:00,shipped,0.333333,0.363636,0.0,...,59 rue de l'abbaye,nan,reims,nan,51100,france,emea,henriot,paul,small
2,0.104615,0.384615,0.928063,0.058824,0.250150,7/1/2003 0:00,shipped,0.666667,0.545455,0.0,...,27 rue du colonel pierre avia,nan,paris,nan,75508,france,emea,da cunha,daniel,medium
3,0.138462,0.428571,0.771061,0.294118,0.240030,8/25/2003 0:00,shipped,0.666667,0.636364,0.0,...,78934 hillside dr.,nan,pasadena,ca,90003,usa,nan,young,julie,medium
4,0.181538,0.472527,1.000000,0.764706,0.347273,10/10/2003 0:00,shipped,1.000000,0.818182,0.0,...,7734 strong st.,nan,san francisco,ca,nan,usa,nan,brown,julie,medium

In [ ]:
df.to_csv('/content/ventas_normalizado.csv', index=False)

print("✅ Archivo guardado como ventas_normalizado.csv")

✅ Archivo guardado como ventas_normalizado.csv

In [ ]:
from google.colab import files
files.download('/content/ventas_normalizado.csv')